;;; ui.el -*- lexical-binding: t; -*-

(setq doom-font (font-spec :family "MonoLisa" :size 18)
      doom-theme nil
      display-line-numbers-type 'relative)

(defun crab/apply-tokyonight-storm-faces ()
  (custom-set-faces!
    '(default :background "#24283b" :foreground "#c0caf5")
    '(minibuffer-prompt :background "#24283b" :foreground "#7aa2f7" :weight bold)
    '(default-italic :background "#24283b")
    '(cursor :background "#c0caf5")
    '(fringe :background "#24283b")
    '(solaire-default-face :background "#24283b")
    '(solaire-fringe-face :background "#24283b")
    '(solaire-hl-line-face :background "#292e42")
    '(vertical-border :foreground "#1f2335")
    '(header-line :background "#24283b" :foreground "#7aa2f7" :box nil)
    '(mode-line-buffer-id :background "#24283b" :foreground "#c0caf5" :weight bold)
    '(region :background "#2e3c64" :foreground "#c0caf5")
    '(secondary-selection :background "#292e42")
    '(hl-line :background "#292e42")
    '(line-number :background "#24283b" :foreground "#565f89")
    '(line-number-current-line :background "#24283b" :foreground "#c0caf5")
    '(mode-line :background "#24283b" :foreground "#c0caf5" :box nil :overline nil :underline nil)
    '(mode-line-inactive :background "#24283b" :foreground "#565f89" :box nil :overline nil :underline nil)
    '(mode-line-highlight :background "#24283b" :foreground "#7aa2f7" :box nil)
    '(mode-line-emphasis :background "#24283b" :foreground "#7aa2f7")
    '(doom-modeline-bar :background "#24283b")
    '(doom-modeline-buffer-path :background "#24283b" :foreground "#7aa2f7" :box nil)
    '(doom-modeline-buffer-file :background "#24283b" :foreground "#c0caf5" :box nil)
    '(doom-modeline-buffer-major-mode :background "#24283b" :foreground "#bb9af7" :box nil)
    '(doom-modeline-buffer-encoding :background "#24283b" :foreground "#565f89" :box nil)
    '(doom-modeline-buffer-eol :background "#24283b" :foreground "#565f89" :box nil)
    '(doom-modeline-buffer-minor-mode :background "#24283b" :foreground "#565f89")
    '(doom-modeline-project-dir :background "#24283b" :foreground "#73daca")
    '(doom-modeline-info :background "#24283b" :foreground "#73daca")
    '(doom-modeline-warning :background "#24283b" :foreground "#e0af68")
    '(doom-modeline-urgent :background "#24283b" :foreground "#f7768e")
    '(doom-modeline-buffer-modified :background "#24283b" :foreground "#ff9e64" :weight bold)
    '(evil-normal-state :background "#24283b" :foreground "#7aa2f7")
    '(evil-insert-state :background "#24283b" :foreground "#9ece6a")
    '(evil-visual-state :background "#24283b" :foreground "#7dcfff")
    '(evil-motion-state :background "#24283b" :foreground "#e0af68")
    '(evil-replace-state :background "#24283b" :foreground "#f7768e")
    '(evil-operator-state :background "#24283b" :foreground "#ff9e64")
    '(evil-emacs-state :background "#24283b" :foreground "#bb9af7")
    '(doom-modeline-evil-normal-state :background "#24283b" :foreground "#7aa2f7" :weight bold :box nil)
    '(doom-modeline-evil-insert-state :background "#24283b" :foreground "#9ece6a" :weight bold :box nil)
    '(doom-modeline-evil-visual-state :background "#24283b" :foreground "#7dcfff" :weight bold :box nil)
    '(doom-modeline-evil-motion-state :background "#24283b" :foreground "#e0af68" :weight bold :box nil)
    '(doom-modeline-evil-replace-state :background "#24283b" :foreground "#f7768e" :weight bold :box nil)
    '(doom-modeline-evil-operator-state :background "#24283b" :foreground "#ff9e64" :weight bold :box nil)
    '(doom-modeline-evil-emacs-state :background "#24283b" :foreground "#bb9af7" :weight bold :box nil)
    '(font-lock-comment-face :foreground "#565f89" :slant italic)
    '(font-lock-doc-face :foreground "#6b7394" :slant italic)
    '(font-lock-keyword-face :foreground "#bb9af7" :slant italic)
    '(font-lock-function-name-face :foreground "#7aa2f7" :slant italic)
    '(font-lock-variable-name-face :foreground "#c0caf5")
    '(font-lock-string-face :foreground "#9ece6a")
    '(font-lock-constant-face :foreground "#ff9e64")
    '(link :foreground "#73daca" :underline t)
    '(internal-border :background "#24283b")
    '(completions-common-part :background "#24283b" :foreground "#7dcfff" :weight bold)
    '(completions-first-difference :background "#24283b" :foreground "#ff9e64")
    '(lazy-highlight :background "#292e42" :foreground "#c0caf5")
    '(match :background "#2e3c64" :foreground "#c0caf5" :weight bold)
    '(isearch :background "#7aa2f7" :foreground "#1f2335" :weight bold)
    '(vertico-current :background "#292e42" :foreground "#c0caf5")
    '(vertico-group-title :background "#24283b" :foreground "#bb9af7" :weight bold)
    '(vertico-group-separator :background "#24283b" :foreground "#565f89")
    '(marginalia-documentation :background "#24283b" :foreground "#565f89")
    '(marginalia-key :background "#24283b" :foreground "#73daca")
    '(marginalia-type :background "#24283b" :foreground "#bb9af7")
    '(doom-dashboard-banner :foreground "#7aa2f7")
    '(doom-dashboard-footer :foreground "#565f89")
    '(doom-dashboard-loaded :foreground "#9ece6a")
    '(doom-dashboard-menu-title :foreground "#bb9af7")
    '(doom-dashboard-menu-desc :foreground "#565f89")
    '(doom-dashboard-buffer-name :foreground "#7dcfff")
    '(doom-dashboard-buffer-path :foreground "#565f89")
    '(doom-dashboard-footer-icon :foreground "#73daca")
    '(vertico-posframe :background "#24283b" :foreground "#c0caf5")
    '(vertico-posframe-border :background "#7aa2f7")))

(crab/apply-tokyonight-storm-faces)
(add-hook 'doom-load-theme-hook #'crab/apply-tokyonight-storm-faces)
(add-hook 'window-setup-hook #'crab/apply-tokyonight-storm-faces)

(after! doom-modeline
  (crab/apply-tokyonight-storm-faces))

(use-package! vertico-posframe
  :when (display-graphic-p)
  :after vertico
  :config
  (setq vertico-posframe-border-width 12
        vertico-posframe-parameters '((left-fringe . 12)
                                      (right-fringe . 12))
        vertico-posframe-poshandler #'posframe-poshandler-frame-center)
  (vertico-posframe-mode 1))
