#!/usr/bin/env bash
set -euo pipefail

DEFAULT_BG="#282a36"
CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/tmux"
CONF_PATH="$CONF_DIR/local-status.conf"

bg="${TMUX_STATUS_BG:-$DEFAULT_BG}"

# validate color: #RRGGBB
if [[ ! "$bg" =~ ^#[0-9A-Fa-f]{6}$ ]]; then
  echo "warn: invalid TMUX_STATUS_BG '$bg', fallback to $DEFAULT_BG" >&2
  bg="$DEFAULT_BG"
fi

mkdir -p "$CONF_DIR"
cat >"$CONF_PATH" <<EOF
# Auto-generated by generate_local_status.sh
set -g @status_bg "$bg"
EOF

echo "tmux status background written to $CONF_PATH ($bg)"
