# -- hooks
set-hook -gu client-attached
set-hook -g client-attached 'run -b "~/.config/tmux/scripts/hooks/dispatch.sh client-attached #{client_tty}"'
set-hook -gu client-detached
set-hook -g client-detached 'run -b "~/.config/tmux/scripts/hooks/dispatch.sh client-detached #{client_tty}"'
run-shell "~/.config/tmux/scripts/hooks/dispatch.sh bootstrap-sync"

set-hook -ag after-select-window 'run-shell "~/.config/tmux/scripts/hooks/dispatch.sh after-select-window \"#{pane_current_path}\""'

set-hook -gu session-created
set-hook -ag session-created 'run -b "~/.config/tmux/scripts/hooks/dispatch.sh session-created"'

set-hook -gu session-renamed
set-hook -g session-renamed 'run -b "~/.config/tmux/scripts/hooks/dispatch.sh session-renamed"'

set-hook -gu session-closed
set-hook -ag session-closed 'run -b "~/.config/tmux/scripts/hooks/dispatch.sh session-closed"'

if-shell -F '#{session_attached}' 'run-shell "~/.config/tmux/scripts/hooks/dispatch.sh bootstrap-sync"'
