-- Plugins module initialization
require("plugins.appearance")
require("plugins.completion")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.debugging")
require("plugins.file_explorer")
require("plugins.markdown")
require("plugins.repl")
require("plugins.editing_helpers")
require("plugins.config")
require("plugins.keymaps")
